### ISSUE TITLE
description of the files and implementation

### ISSUE THREAD

**Issue by JoannaZ84** [akiotakahashi/MersenneTwister#2]
Hi Akio, I wanted to implement Saito's and Matsumoto's package for 128-bits SIMD oriented Mersenne Twister in c#. I came across your Mersenne Twister package 1.0.5. However, I do not find docs about te content. You have SFMT, as in original paper, but it does not seem to use SIMD instructions? it is MT for 128 words while your MT is for 64-bits? Could you add some docs on the files please, best,Joanna

**Comment by akiotakahashi** [comment]
This MersenneTwister Nuget package doesn't use SIMD instructions (pure C#). It's a translation from original SFMT code with SIMD-disabled configuration.
