### ISSUE TITLE
Random.NextBytes() is not implemented

### ISSUE THREAD

**Issue by mattiasflodin** [akiotakahashi/MersenneTwister#3]
[The implementation of Random.NextBytes()](https://github.com/akiotakahashi/MersenneTwister/blob/b4d04077bb3566816322f14d5f17749c597e3fe8/MersenneTwister/RandomBase.cs#L26) does nothing, leaving the input buffer unchanged.

This makes me a bit worried about the quality of the library. I see a MersenneTwister.Tests directory. Is NextBytes() never tested at all?

**Comment by akiotakahashi** [comment]
> Is NextBytes() never tested at all?

Yes.
But it's a bug that the method left blank.

When we need to generate a random byte block, it's not the best way to generate UInt32/64 or Double values because MT holds random byte blocks internally. So I didn't implements the method yet.

**Comment by twilek** [comment]
The current implementation is a bit buggy, leaves the last positions in the buffer unset if the length isn't an exact multiple of 8 or 4

Here is a fast, ugly and unoptimized fix for RandomBase64 that at least works:

     protected sealed override void GenerateBytes(byte[] buffer)
     {
        if (buffer == null)
        {
           throw new ArgumentNullException(nameof(buffer));
        }
     
        for (var i = 7; i < buffer.Length + 7; i += 8)
        {
           var val = GenerateUInt64();
           var currentIndex = i - 7;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)val;
           currentIndex = i - 6;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 8);
           currentIndex = i - 5;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 16);
           currentIndex = i - 4;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 24);
           currentIndex = i - 3;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 32);
           currentIndex = i - 2;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 40);
           currentIndex = i - 1;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 48);
           currentIndex = i;
           if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 56);
        }
     }

And for RandomBase32

    protected sealed override void GenerateBytes(byte[] buffer)
    {
       if (buffer == null)
       {
       throw new ArgumentNullException(nameof(buffer));
       }
    
       for (var i = 3; i < buffer.Length + 3; i += 4)
       {
          var val = GenerateUInt32();
          var currentIndex = i - 3;
          if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)val;
          currentIndex = i - 2;
          if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 8);
          currentIndex = i - 1;
          if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 16);
          currentIndex = i;
          if (buffer.Length > currentIndex) buffer[currentIndex] = (byte)(val >> 24);
       }
    }

**Comment by akiotakahashi** [comment]
Thanks @twilek.

I made fixes to your points in https://github.com/akiotakahashi/MersenneTwister/commit/b3085809abae995c4a0774893df3807179275dba and write implementation of RandomBase.NextBytes and tests.

**Comment by akiotakahashi** [comment]
A new version 1.0.6 is now listed on nuget. Please check it.
